#-------------------------------
# Site Settings
title: Dr. John Torrens
logo: # You can add own logo. For example '/images/logo.png'.
description: This is a protfolio site of Dr. John Torrens. 
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Speaker Request'
      url: '/speaker-request/'
    - title: 'Announcements'
      url: '/announcements/'
    - title: 'Investments'
      url: '/investments/'



#-------------------------------
# Author Settings
author:
  author__name: John Torrens
  author__bio: So, If you're looking for designs that have a high visual impact on your target audience, while also aligning with your brand, Let's talk about your project in more detail.
  author__avatar: '/images/John/torrensnotiesquare.jpg'

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/johnmtorrens/"}
- {icon: "ion-md-mail", link: "mailto:jtorrens@syr.edu"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/watch?v=XdT4DIiX7Nk"}
- {icon: "ion-md-globe", link: "https://whitman.syracuse.edu/faculty-and-research/faculty-staff-directory/details/jtorrens"}


# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Entrepreneur, Educator, TEDx Speaker, Author
  hero__description: >
    Dr. John Torrens is an award-winning professor and three-time Inc. 5000 entrepreneur with 25 years of leading high-growth companies. John teaches entrepreneurship and strategy at Syracuse University and serves as the President of Sprout Therapy Group. <a target="_blank" href="/about">Learn more</a> about John's work,  <a target = "_blank" href="/speaker-request/">invite him to speak</a> at your event, or buy his book <a target="_blank" href="https://shorturl.at/PMcVJ"> <i>Lightning in a Bottle: How Entrepreneurs Can Harness Their ADHD to Win </i></a>.
  hero__image: '/images/John/torrensnotiesquare.jpg'


book:
  book__title: >
    Lightening in Bottle: How Entrepreneurs Can Harness Their ADHD to Win
  book__description: >
    This book will help entrepreneurs, (or those who love them), discover how to harness their ADHD for maximum creativity, focus, and productivity, while learning how to manage the downsides and eliminate obstacles, so that they can achieve even more success. <a href= "https://www.amazon.com/Lightning-Bottle-Entrepreneurs-Harness-Their/dp/B08SGMZZ6Y/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.N9_ihbq4RpjcCMspezYnAw.dwnwERJrNn5DvxA5xX-EqhMyKD4atUtTPI8zjHVoZ7k&qid=1721567840&sr=1-1"> Get it today</a>.
  book__image: '/images/John/lighteningsquare.png'

ted:
  ted__title: Watch John’s TEDx Talk
  ted__description: >
    Did you know that 62% of highly successful entrepreneurs have traits consistent with ADHD? Is this a coincidence, or is there more to the story? In his talk, In this fascinating talk, John Torrens uses research and his years of experience to show how this is no mere coincidence — ADHD can be a "entrepreneur's superpower."
  ted__url: 'https://www.youtube.com/embed/XdT4DIiX7Nk?si=yEhQJzimROnFON4k'

#-------------------------------
# Newsletter
mailchimp:  # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address...
mailchimp__button__text: Get updates


#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Projects
  projects__description: Explore John's portfolio of innovative projects, ventures, and achievements


#-------------------------------
# Testimonials Section
testimonial__title: What clients say
testimonial__description:

testimonial__items:
  - name: "Aspen Carder"
    image: "/images/client-1.jpg"
    designation: "Lettering Artist"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Lydia Siphron"
    image: "/images/client-2.jpg"
    designation: "Designer"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Craig Vaccaro"
    image: "/images/client-3.jpg"
    designation: "Web developer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Anika Calzoni"
    image: "/images/client-4.jpg"
    designation: "Lettering Artist"
    link: "https://facebook.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Marcus Botosh"
    image: "/images/client-5.jpg"
    designation: "Full Stack Designer"
    link: "https://twitter.com/"
    content : "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"


#-------------------------------
# Blog Section
blog__settings:
  blog__title: News
  blog__description:


#-------------------------------
# Gallery Footer Settings
gallery:
  gallery__images:
    - alt: 'Rest'
      url: '/images/John/sproutsquare.png'
    - alt: 'Lifestyle'
      url: '/images/John/whitmansquare.png'
    - alt: 'Hobby'
      url: '/images/John/lighteningsquare.png'
    - alt: 'Notes'
      url: '/images/John/torrensnotiesquare.jpg'


#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Speaker Request'
      url: '/speaker-request/'
    - title: 'Invesments'
      url: '/investments/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'News'
      url: '/blog/'


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: >
        <p>John is an experienced speaker with a portfolio of presentations below that fit a wide variety of audiences. If you would like to bring John to your conference, business, or classroom guest lecture, contact him using the form below or book a 1-on-1 meeting directly with John.</p>
        <a target="_blank" href="https://outlook.office.com/bookwithme/user/0850756ce9ac43f685c14d8a8928fb92%40syr.edu?anonymous&isanonymous=true" class="button button--primary">Book Appointment</a>  
  topics:
    - title: ADHD as an Entrepreneur’s Superpower.  
      discription: >
        ADHD can be very debilitating condition, often resulting in undesirable business and life outcomes.  However, in the context of entrepreneurship, certain types of ADHD have shown to be an incredible advantage if harnessed properly.  In this session you will learn how to maximize the upside while minimizing the downside to allow your natural entrepreneurial abilities to shine.
    - title: Is your good idea a good business opportunity?  
      discription: >
        Many people have great ideas, but how do you know whether those ideas can be viable business opportunities.  Learn a repeatable model to test your ideas for viability before you spend the time, energy, and money launching a business and bringing a product to market.
    - title:> "Selling your company  Best practices for the best exit." 
    - title: >
        Selling your company:  Best practices for the best exit.   
      discription: >
        Everyone leaves their company one way or another, so it is important to be intentional about the way you run your business to maximize your inevitable exit.  Learn best practices for the greatest wealth creation strategies that were collected from 50 in-depth interviews of founder/CEOs who have exited their businesses.  Not all exits are equal.  This session will teach you how to maximize yours
    - title: Growth through mergers and acquisitions  
      discription: >
        Regardless of how your company has been funded, growth is necessary.  Organic growth is great, btu there is often an upper limit to how much you can grow organically.  Before you consider taking on a acquisition, learn from someone who has done it several times and teaches it at a leading university.  This session will equip you with the knowledge and skills to approach an M&A strategy for maximum potential.  Learn about the process, best practices, pitfalls and traps to avoid in the highly engaging session.
    - title: Negotiations and Dealmaking. 
      discription: >
        Life is a series of negotiations.  In the context of entrepreneurship, the deals you make, and the deals you don’t, have profound and long-lasting effects.  Learn how to prepare and execute a high impact negotiation from an award-winning professor and master deal maker.  In this session you will learn advanced negotiation concepts and then practice in simulated negotiations for feedback.  Learning to be a better negotiator is best done by doing it!
    - title: Becoming the CEO of your Own Health 
      discription: >
        Entrepreneurs and executive work famously hard, often to their own detriment.  You have dashboards for your business, but probably not for your own health.  Instead of spending a life time creating wealth only to see it evaporate in your final decade while you manage chronic disease that was largely preventable, why not develop your strategic plan to enjoy the fruits of your labor well into your final, healthy decades.
    - title: Finding joy and happiness in business.    
      discription: >
        People all want the same thing:  joy, happiness, love, and a sense of purpose. If everyone wants these things, then the trend toward more anxiety, depression, and less overall enjoyment of life and business is quite curious.  Happy people live on average 7 years longer than unhappy people, and for successful business people, this is great news in terms of getting every bit of joy out of the life you worked so hard for.  This session will teach you the basics of happiness science and how to claim the joy that is already inside you. Learn what the worlds happiest people know and do, and take home practical techniques to feel more happy and joyful every day.



# NOTE
# Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id